image: maven:3.3.9-jdk-8
variables:
  TZ: Asia/Shanghai
  MAVEN_CLI_OPTS: "-s /cache/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=/cache/repository"
stages:
  - build
  - docker
  - k8s
  - notify
build:production:
  stage: deploy
  tags:
    - development
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~/^release+.[0-9]{12}/
  script:
    - mvn versions:set -DnewVersion=1.0.$CI_PIPELINE_ID
    - mvn $MAVEN_CLI_OPTS clean deploy -U -am -DskipTests $MAVEN_OPTS -Pproduction
    - cp project/target/project.jar /deploy/project.jar
docker:production:
  image: docker:19.03.8
  stage: docker
  tags:
    - development
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~/^release+.[0-9]{12}/
  script:
    - mkdir target
    - cp /deploy/project.jar target/app.jar
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.youdockerserver.com
    - docker build -t registry.youdockerserver.com/namespace/project:$CI_PIPELINE_ID .
    - docker push registry.youdockerserver.com/namespace/project:$CI_PIPELINE_ID
    - docker rmi registry.youdockerserver.com/namespace/project:$CI_PIPELINE_ID
k8s:production:
  image: linkyard/kubectl
  stage: k8s
  tags:
    - development
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~/^release+.[0-9]{12}/
  script:
    - mkdir -p ~/.kube
    - echo $kube_config |base64 -d > ~/.kube/config
    - sed -i "s/IMAGE_TAG/$CI_PIPELINE_ID/g" deployment.yaml
    - cat deployment.yaml
    - kubectl apply -f deployment.yaml --validate=false
success:
  image: wanghws/curl:1.1
  stage: notify
  tags:
    - development
  script:
    - curl -s -d  "message=success" notify.domain.com
  when: on_success
failure:
  image: wanghws/curl:1.1
  stage: notify
  tags:
    - development
  script:
    - curl -s -d  "message=failure" notify.domain.com
  when: on_failure
